from fastapi.responses import HTMLResponse


ADMIN_HTML = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>青葵管理后台</title>
<style>
:root{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#17202a;background:#f5f7fa}body{margin:0}header{background:#155eef;color:#fff;padding:18px 24px;display:flex;justify-content:space-between;align-items:center}main{max-width:1380px;margin:20px auto;padding:0 16px;display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(340px,1fr))}.panel{background:#fff;border:1px solid #dfe3eb;border-radius:8px;padding:16px;box-shadow:0 1px 2px #0000000b}h2{font-size:18px;margin:0 0 12px}label{display:block;font-size:13px;color:#59636e;margin:8px 0 4px}input,select,textarea{width:100%;box-sizing:border-box;border:1px solid #cbd2dc;border-radius:5px;padding:8px;font:inherit}textarea{min-height:72px;resize:vertical}button{border:0;border-radius:5px;background:#155eef;color:#fff;padding:8px 12px;cursor:pointer;margin-top:10px}button.secondary{background:#687386}button.danger{background:#d92d20}button.small{padding:5px 8px;margin:0 4px 0 0;font-size:12px}.row{display:flex;gap:8px}.row>*{flex:1}pre{background:#101828;color:#d0d5dd;padding:10px;border-radius:5px;max-height:250px;overflow:auto;font-size:12px;white-space:pre-wrap}.wide{grid-column:1/-1}.muted{color:#667085;font-size:13px}.toolbar{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;align-items:end}.table-wrap{overflow:auto;border:1px solid #e4e7ec;border-radius:5px;margin-top:12px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;vertical-align:top;padding:9px;border-bottom:1px solid #eaecf0}th{background:#f9fafb;color:#475467;white-space:nowrap}td.blockers{min-width:260px;color:#b42318}td.preview{min-width:280px;max-width:460px;white-space:pre-wrap}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:8px}.editor{border-top:1px solid #eaecf0;margin-top:14px;padding-top:6px}
</style></head><body><header><strong>青葵计划 · 管理后台</strong><span id="status">未连接</span></header>
<main>
<section class="panel"><h2>管理员令牌</h2><label>Access Token</label><input id="token" type="password" placeholder="粘贴登录后获得的 JWT"><div class="row"><button onclick="saveToken()">保存令牌</button><button class="secondary" onclick="loadLogs()">审计日志</button></div><p class="muted">令牌仅保存在当前浏览器会话。</p></section>
<section class="panel wide"><h2>知识候选审核队列</h2><div class="toolbar"><div><label>学科</label><input id="candidateSubject" value="数学"></div><div><label>年级</label><input id="candidateGrade" value="高一"></div><div><label>教材</label><input id="candidateVersion" value="人教A版"></div><div><label>关键词</label><input id="candidateQ" placeholder="节点或章节"></div><div><label>阻断原因</label><select id="candidateBlocker"><option value="">全部</option><option>缺少常见错误</option><option>缺少典型题型</option><option>缺少知识关系</option><option>内容仍包含待审核或演示占位语</option></select></div><button onclick="loadCandidateQueue(true)">查询</button></div><div class="table-wrap"><table><thead><tr><th>节点</th><th>章节</th><th>阻断原因</th><th>来源</th><th>操作</th></tr></thead><tbody id="candidateRows"></tbody></table></div><div class="pager"><button class="secondary small" onclick="changeCandidatePage(-1)">上一页</button><span id="candidateMeta" class="muted">尚未加载</span><button class="secondary small" onclick="changeCandidatePage(1)">下一页</button></div></section>
<section class="panel wide"><h2>节点审核编辑</h2><label>节点 ID</label><input id="nodeId" placeholder="从候选队列选择"><div class="row"><div><label>定义</label><textarea id="nodeDefinition"></textarea></div><div><label>解释</label><textarea id="nodeExplanation"></textarea></div></div><div class="row"><div><label>常见错误（每行一条）</label><textarea id="nodeErrors"></textarea></div><div><label>典型题型（每行一条）</label><textarea id="nodeQuestionTypes"></textarea></div></div><div class="row"><button onclick="saveNodeReview()">保存审核编辑</button><button onclick="nodeAction('publish')">通过并发布</button><button class="danger" onclick="nodeAction('withdraw')">下线</button></div><label>恢复版本号</label><div class="row"><input id="version" type="number" min="1" value="1"><button class="secondary" onclick="restoreNode()">恢复为草稿</button><button class="secondary" onclick="loadVersions()">版本历史</button></div></section>
<section class="panel wide"><h2>来源与文档</h2><div class="toolbar"><div><label>关键词</label><input id="documentQ" placeholder="标题或对象地址"></div><div><label>学科</label><input id="documentSubject" value="数学"></div><div><label>状态</label><select id="documentFilterStatus"><option value="">全部</option><option>indexed</option><option>text_ready</option><option>processing</option><option>failed</option><option>archived</option></select></div><button onclick="loadDocuments()">查询文档</button><button class="secondary" onclick="loadSources()">查询来源</button></div><div class="table-wrap"><table><thead><tr><th>文档</th><th>范围</th><th>状态 / 分块</th><th>授权</th><th>操作</th></tr></thead><tbody id="documentRows"></tbody></table></div><div class="editor"><div class="row"><div><label>来源 ID（留空则新建）</label><input id="sourceId" readonly></div><div><label>来源标题</label><input id="sourceTitle"></div><div><label>授权状态</label><select id="sourceAuthorization"><option>self_owned</option><option>authorized</option><option>public_domain</option><option>internal_demo</option></select></div></div><div class="row"><div><label>出版方</label><input id="sourcePublisher"></div><div><label>版本</label><input id="sourceEdition"></div><div><label>定位</label><input id="sourceLocation"></div></div><div class="row"><button onclick="saveSource()">保存来源</button><button class="secondary" onclick="clearSourceEditor()">新建来源</button></div><label>文档 ID</label><input id="documentId" readonly><div class="row"><div><label>标题</label><input id="documentTitle"></div><div><label>年级</label><input id="documentGrade"></div><div><label>教材版本</label><input id="documentVersion"></div></div><div class="row"><div><label>章节</label><input id="documentChapter"></div><div><label>文档角色</label><input id="documentRole"></div><div><label>授权状态</label><select id="documentAuthorization"><option>self_owned</option><option>authorized</option><option>public_domain</option><option>pending_review</option></select></div><div><label>状态</label><select id="documentStatus"><option value="">保持当前</option><option>text_ready</option><option>processing</option><option>failed</option><option>archived</option></select></div></div><button onclick="saveDocument()">保存文档元数据</button></div></section>
<section class="panel wide"><h2>图谱完整性</h2><div class="toolbar"><div><label>学科（留空检查全部）</label><input id="integritySubject" value="数学"></div><button onclick="loadIntegrity()">检查悬空节点、重复节点、跨学科关系与前置环</button></div><p class="muted">检查结果不会自动修改图谱；请在关系工作区逐项确认后处理。</p></section>
<section class="panel wide"><h2>公式审核队列</h2><div class="toolbar"><div><label>状态</label><select id="formulaFilterStatus"><option>pending</option><option>approved</option><option>rejected</option><option>all</option></select></div><div><label>学科</label><input id="formulaSubject" value="数学"></div><div><label>最高置信度</label><input id="formulaConfidence" type="number" min="0" max="1" step="0.01" placeholder="例如 0.8"></div><button onclick="loadFormulaQueue(true)">查询</button></div><div class="table-wrap"><table><thead><tr><th>文档 / 章节</th><th>LaTeX</th><th>置信度</th><th>状态</th><th>操作</th></tr></thead><tbody id="formulaRows"></tbody></table></div><div class="pager"><button class="secondary small" onclick="changeFormulaPage(-1)">上一页</button><span id="formulaMeta" class="muted">尚未加载</span><button class="secondary small" onclick="changeFormulaPage(1)">下一页</button></div><div class="editor"><label>公式分块 ID</label><input id="formulaId" readonly><label>修订后的 LaTeX</label><textarea id="formulaLatex"></textarea><div class="row"><div><label>审核状态</label><select id="formulaStatus"><option>approved</option><option>rejected</option><option>pending</option></select></div><div><label>审核备注</label><input id="formulaNote"></div></div><button onclick="saveFormulaReview()">提交公式审核</button></div></section>
<section class="panel wide"><h2>知识关系</h2><div class="toolbar"><div><label>节点筛选</label><input id="edgeNodeFilter" placeholder="节点 ID"></div><button class="secondary" onclick="loadEdges()">查询关系</button></div><div class="table-wrap"><table><thead><tr><th>源节点</th><th>类型</th><th>目标节点</th><th>说明</th><th>操作</th></tr></thead><tbody id="edgeRows"></tbody></table></div><div class="editor"><label>关系 ID（留空则新建）</label><input id="edgeId" readonly><label>源节点 / 目标节点</label><div class="row"><input id="source" placeholder="源节点"><input id="target" placeholder="目标节点"></div><label>关系类型</label><select id="edgeType"><option value="prerequisite">前置</option><option value="confused_with">易混</option><option value="question_type">题型</option><option value="related">相关</option><option value="extension">拓展</option></select><label>说明</label><input id="edgeExplanation" value="管理员维护的知识关系"><div class="row"><button onclick="saveEdge()">保存关系</button><button class="secondary" onclick="clearEdgeEditor()">新建关系</button><button class="danger" onclick="deleteEdge()">删除所选关系</button></div></div></section>
<section class="panel"><h2>反馈审核</h2><label>反馈 ID</label><input id="feedbackId"><label>审核状态</label><select id="feedbackStatus"><option>accepted</option><option>resolved</option><option>rejected</option><option>pending</option></select><label>审核备注</label><input id="feedbackNote"><button onclick="reviewFeedback()">提交审核</button><button class="secondary" onclick="loadFeedback()">待审核列表</button></section>
<section class="panel"><h2>用户额度</h2><label>用户 ID</label><input id="userId"><label>调整数量（可为负）</label><input id="amount" type="number" value="100"><label>原因</label><input id="reason" value="后台调整"><button onclick="adjustCredits()">调整额度</button></section>
<section class="panel"><h2>模型调用与运行告警</h2><label>开始时间</label><input id="costStart" type="datetime-local"><label>结束时间</label><input id="costEnd" type="datetime-local"><div class="row"><div><label>功能</label><select id="costFeature"><option value="">全部</option><option>qa_knowledge</option><option>qa_problem</option><option>qa_error</option><option>qa_review</option><option>qa_explore</option><option>qa_verify</option><option>mistake_analysis</option><option>qa_legacy</option></select></div><div><label>供应商</label><input id="costProvider" placeholder="deepseek"></div></div><div class="row"><button onclick="loadCosts()">查询调用量、失败率与延迟</button><button class="secondary" onclick="loadOperationalAlerts()">检查当前告警</button></div></section>
<section class="panel wide"><h2>投稿审核</h2><div class="toolbar"><div><label>状态</label><select id="contributionStatus"><option value="screened">待人工审核</option><option value="review_failed">初审失败</option><option value="queued">排队中</option><option value="approved">已通过</option><option value="rejected">已拒绝</option><option value="">全部</option></select></div><button onclick="loadContributions()">查询投稿</button><button class="secondary" onclick="settleContributionRewards()">结算到期奖励</button></div><div class="table-wrap"><table><thead><tr><th>标题</th><th>类型 / 状态</th><th>AI 初审</th><th>用户</th><th>操作</th></tr></thead><tbody id="contributionRows"></tbody></table></div><div class="editor"><label>投稿 ID</label><input id="contributionId" readonly><div class="row"><div><label>决定</label><select id="contributionDecision"><option>approved</option><option>rejected</option></select></div><div><label>奖励额度（生产默认关闭）</label><input id="contributionReward" type="number" min="0" value="0"></div></div><label>审核说明</label><textarea id="contributionNote"></textarea><div class="row"><button onclick="reviewContribution()">提交人工审核</button><button class="secondary" onclick="retryContribution()">重试 AI 初审</button></div></div></section>
<section class="panel wide"><h2>学校、班级与试点准入</h2><p class="muted">学生邀请码需先完成学校、学生自愿参与及必要的监护人授权确认。仅记录授权依据，不得录入监护人姓名、电话或证件信息；邀请码明文仅在创建时显示。</p><div class="row"><div><label>学校名称</label><input id="schoolName"></div><div><label>学校代码</label><input id="schoolCode"></div><button onclick="createSchool()">创建学校</button></div><label>学校 ID</label><input id="schoolId"><div class="row"><div><label>班级名称</label><input id="className"></div><div><label>年级</label><input id="classGrade" value="高一"></div><div><label>学年</label><input id="classYear" value="2026-2027"></div></div><div class="row"><button onclick="createClassroom()">创建班级</button><button class="secondary" onclick="loadClasses()">查询班级</button></div><label>班级 ID</label><input id="classId"><div class="row"><div><label>邀请角色</label><select id="inviteRole"><option>student</option><option>teacher</option></select></div><div><label>最大使用次数</label><input id="inviteUses" type="number" min="1" value="1"></div><div><label>有效小时</label><input id="inviteHours" type="number" min="1" value="72"></div></div><div class="row"><button onclick="createInvite()">创建邀请码</button><button class="secondary" onclick="loadClassOverview()">匿名班级概览</button></div><div class="editor"><h2>学生试点准入</h2><label>参与者用户 ID</label><input id="pilotParticipantId" placeholder="36 位用户 ID"><div class="row"><div><label>学校已授权</label><select id="pilotSchoolAuthorized"><option value="true">是</option><option value="false">否</option></select></div><div><label>学生自愿参与</label><select id="pilotVoluntary"><option value="true">是</option><option value="false">否</option></select></div><div><label>需要监护人授权</label><select id="pilotGuardianRequired"><option value="true">是</option><option value="false">否</option></select></div><div><label>监护人授权已确认</label><select id="pilotGuardianConfirmed"><option value="true">是</option><option value="false">否</option></select></div></div><label>授权依据（只写文件编号或确认方式）</label><input id="pilotApprovalBasis" placeholder="例如：校方审批单编号 / 线下知情同意确认"><div class="row"><button onclick="approvePilotEnrollment()">批准准入</button><button class="secondary" onclick="loadPilotApprovals()">查询准入记录</button><button class="danger" onclick="revokePilotEnrollment()">撤销当前用户准入</button></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>状态</th><th>授权确认</th><th>依据</th><th>操作</th></tr></thead><tbody id="pilotApprovalRows"></tbody></table></div></div></section>
<section class="panel wide"><h2>活动额度</h2><p class="muted">生产默认关闭；兑换码明文仅在创建响应中出现，不写入日志。</p><div class="toolbar"><div><label>活动名称</label><input id="campaignName"></div><div><label>每次额度</label><input id="campaignAmount" type="number" min="1" value="20"></div><div><label>最大兑换</label><input id="campaignMax" type="number" min="1" value="10"></div><div><label>兑换码数量</label><input id="campaignCodes" type="number" min="1" value="1"></div><button onclick="createCampaign()">创建活动</button><button class="secondary" onclick="loadCampaigns()">查询活动</button></div></section>
<section class="panel wide"><h2>试点运营与数据清理</h2><div class="toolbar"><div><label>开始时间</label><input id="pilotStart" type="datetime-local"></div><div><label>结束时间</label><input id="pilotEnd" type="datetime-local"></div><button onclick="loadPilotMetrics()">查看试点指标</button><button class="secondary" onclick="downloadPilotExport()">下载匿名 JSON</button></div><div class="editor"><label>待清理学生用户 ID（每行一个，最多 100 个）</label><textarea id="pilotCleanupIds" placeholder="必须先从用户列表确认精确 ID"></textarea><div class="row"><button class="secondary" onclick="previewPilotCleanup()">预览清理范围</button><div><label>预期清理数量</label><input id="pilotCleanupCount" type="number" min="1" value="1"></div><div><label>确认短语</label><input id="pilotCleanupConfirmation" placeholder="DELETE_PILOT_DATA"></div><button class="danger" onclick="executePilotCleanup()">执行不可恢复清理</button></div></div></section>
<section class="panel wide"><h2>用户与权限</h2><div class="toolbar"><div><label>关键词</label><input id="userQ" placeholder="用户名、昵称或邮箱"></div><div><label>角色</label><select id="userRole"><option value="">全部</option><option>student</option><option>content_admin</option><option>admin</option></select></div><div><label>状态</label><select id="userActive"><option value="">全部</option><option value="true">正常</option><option value="false">冻结</option></select></div><button onclick="loadUsers()">查询用户</button></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>余额</th><th>操作</th></tr></thead><tbody id="userRows"></tbody></table></div></section>
<section class="panel wide"><h2>OCR 任务审核</h2><div class="toolbar"><div><label>关键词</label><input id="ocrQ" placeholder="用户名或题目"></div><div><label>状态</label><select id="ocrFilterStatus"><option value="">全部</option><option>queued</option><option>recognizing</option><option>succeeded</option><option>failed</option><option>cancelled</option></select></div><div><label>人工复核</label><select id="ocrReview"><option value="">全部</option><option value="true">需要</option><option value="false">不需要</option></select></div><button onclick="loadOcrTasks()">查询任务</button></div><div class="table-wrap"><table><thead><tr><th>状态</th><th>用户 / 错题</th><th>置信度</th><th>创建时间</th><th>操作</th></tr></thead><tbody id="ocrRows"></tbody></table></div><div class="editor"><label>已选任务 ID</label><input id="ocrTaskId" readonly><div class="row"><button class="danger" onclick="ocrTaskAction('cancel')">取消任务</button><button class="secondary" onclick="ocrTaskAction('retry')">重试任务</button></div></div></section>
<section class="panel wide"><h2>错题内容审核</h2><div class="toolbar"><div><label>题目关键词</label><input id="mistakeQ"></div><div><label>审核状态</label><select id="mistakeFilterStatus"><option value="">全部</option><option>needs_review</option><option>recognized</option><option>confirmed</option><option>approved</option><option>rejected</option></select></div><div><label>关联状态</label><select id="mistakeFilterLink"><option value="">全部</option><option>pending</option><option>confirmed</option><option>rejected</option></select></div><button onclick="loadMistakes()">查询错题</button></div><div class="table-wrap"><table><thead><tr><th>题目</th><th>审核 / 关联</th><th>用户</th><th>操作</th></tr></thead><tbody id="mistakeRows"></tbody></table></div><div class="editor"><label>错题 ID</label><input id="mistakeId" readonly><div class="row"><div><label>审核状态</label><select id="mistakeReviewStatus"><option>approved</option><option>needs_review</option><option>rejected</option><option>confirmed</option></select></div><div><label>错因</label><select id="mistakeCategory"><option value="">不修改</option><option>concept</option><option>reading</option><option>method</option><option>calculation</option><option>expression</option><option>other</option></select></div><div><label>关联状态</label><select id="mistakeLinkStatus"><option>confirmed</option><option>pending</option><option>rejected</option></select></div></div><label>知识节点 ID</label><input id="mistakeNodeId"><label>审核备注 / 错因说明</label><textarea id="mistakeNote"></textarea><button onclick="saveMistakeReview()">提交错题审核</button></div></section>
<section class="panel wide"><h2>结果</h2><pre id="output">准备就绪</pre></section>
</main><script>
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('adminToken')||''; $('token').value=token;
function saveToken(){token=$('token').value.trim();sessionStorage.setItem('adminToken',token);$('status').textContent=token?'已设置令牌':'未连接';}
async function api(path,options={}){if(!token)saveToken();const headers=Object.assign({'Content-Type':'application/json','Authorization':'Bearer '+token},options.headers||{});const r=await fetch('/api'+path,{...options,headers});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok){const detail=data&&data.detail;throw new Error(typeof detail==='string'?detail:detail?JSON.stringify(detail):r.status+' '+r.statusText)}return data}
function show(data){$('output').textContent=JSON.stringify(data,null,2)}
const lines=id=>$(id).value.split('\n').map(x=>x.trim()).filter(Boolean);let candidateOffset=0,formulaOffset=0;const pageSize=25;
function cell(row,text,className=''){const td=document.createElement('td');td.textContent=text??'';if(className)td.className=className;row.appendChild(td);return td}
async function loadCandidateQueue(reset=false){try{if(reset)candidateOffset=0;const p=new URLSearchParams({subject:$('candidateSubject').value,grade:$('candidateGrade').value,textbook_version:$('candidateVersion').value,review_status:'draft',offset:candidateOffset,limit:pageSize});if($('candidateQ').value)p.set('q',$('candidateQ').value);if($('candidateBlocker').value)p.set('blocker',$('candidateBlocker').value);const data=await api('/admin/knowledge/review-queue?'+p);const body=$('candidateRows');body.replaceChildren();for(const item of data.items){const row=document.createElement('tr');cell(row,item.name);cell(row,item.chapter);cell(row,item.blockers.join('；'),'blockers');cell(row,item.source_title+'\n'+item.source_excerpt);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='选择';button.onclick=()=>selectCandidate(item.id);action.appendChild(button);body.appendChild(row)}$('candidateMeta').textContent=`${data.offset+1}-${Math.min(data.offset+data.items.length,data.total)} / ${data.total}`;show(data)}catch(e){show({error:e.message})}}
function changeCandidatePage(direction){const next=Math.max(0,candidateOffset+direction*pageSize);if(next===candidateOffset)return;candidateOffset=next;loadCandidateQueue()}
async function selectCandidate(id){try{const node=await api('/admin/knowledge/nodes/'+encodeURIComponent(id));$('nodeId').value=node.id;$('nodeDefinition').value=node.definition;$('nodeExplanation').value=node.explanation;$('nodeErrors').value=(node.common_errors||[]).join('\n');$('nodeQuestionTypes').value=(node.question_types||[]).join('\n');show(node)}catch(e){show({error:e.message})}}
async function saveNodeReview(){try{const id=encodeURIComponent($('nodeId').value);const body={definition:$('nodeDefinition').value,explanation:$('nodeExplanation').value,common_errors:lines('nodeErrors'),question_types:lines('nodeQuestionTypes'),review_status:'draft',is_active:false};show(await api('/admin/knowledge/nodes/'+id,{method:'PATCH',body:JSON.stringify(body)}));await loadCandidateQueue()}catch(e){show({error:e.message})}}
async function nodeAction(action){try{const data=await api('/admin/knowledge/nodes/'+encodeURIComponent($('nodeId').value)+'/'+action,{method:'POST',body:JSON.stringify({change_note:'管理后台操作'})});show(data);await loadCandidateQueue()}catch(e){show({error:e.message})}}
async function restoreNode(){try{show(await api('/admin/knowledge/nodes/'+encodeURIComponent($('nodeId').value)+'/restore',{method:'POST',body:JSON.stringify({version:Number($('version').value),change_note:'管理后台恢复'})}))}catch(e){show({error:e.message})}}
async function loadVersions(){try{show(await api('/admin/knowledge/nodes/'+encodeURIComponent($('nodeId').value)+'/versions'))}catch(e){show({error:e.message})}}
async function loadNodes(){try{show(await api('/admin/knowledge/nodes'))}catch(e){show({error:e.message})}}
async function loadChapters(){try{show(await api('/admin/knowledge/chapters'))}catch(e){show({error:e.message})}}
function clearSourceEditor(){$('sourceId').value='';$('sourceTitle').value='';$('sourcePublisher').value='';$('sourceEdition').value='';$('sourceLocation').value='';$('sourceAuthorization').value='self_owned'}
function selectSource(item){$('sourceId').value=item.id;$('sourceTitle').value=item.title;$('sourcePublisher').value=item.publisher||'';$('sourceEdition').value=item.edition||'';$('sourceLocation').value=item.location;$('sourceAuthorization').value=item.authorization_status;show(item)}
async function loadSources(){try{const p=new URLSearchParams();if($('documentQ').value)p.set('q',$('documentQ').value);const data=await api('/admin/knowledge/sources?'+p);const body=$('documentRows');body.replaceChildren();for(const item of data){const row=document.createElement('tr');cell(row,item.title);cell(row,(item.publisher||'')+'\n'+(item.edition||''));cell(row,item.location);cell(row,item.authorization_status);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='编辑来源';button.onclick=()=>selectSource(item);action.appendChild(button);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
async function saveSource(){try{const body={title:$('sourceTitle').value.trim(),publisher:$('sourcePublisher').value.trim()||null,edition:$('sourceEdition').value.trim()||null,location:$('sourceLocation').value.trim(),authorization_status:$('sourceAuthorization').value};const id=$('sourceId').value;const data=await api(id?'/admin/knowledge/sources/'+encodeURIComponent(id):'/admin/knowledge/sources',{method:id?'PATCH':'POST',body:JSON.stringify(body)});selectSource(data);await loadSources()}catch(e){show({error:e.message})}}
function selectDocument(item){$('documentId').value=item.id;$('documentTitle').value=item.title;$('documentSubject').value=item.subject||'';$('documentGrade').value=item.grade||'';$('documentVersion').value=item.textbook_version||'';$('documentChapter').value=item.chapter||'';$('documentRole').value=item.document_role||'';$('documentAuthorization').value=item.authorization_status;$('documentStatus').value='';show(item)}
async function loadDocuments(){try{const p=new URLSearchParams({offset:0,limit:50});if($('documentQ').value)p.set('q',$('documentQ').value);if($('documentSubject').value)p.set('subject',$('documentSubject').value);if($('documentFilterStatus').value)p.set('document_status',$('documentFilterStatus').value);const data=await api('/admin/knowledge/documents?'+p);const body=$('documentRows');body.replaceChildren();for(const item of data.items){const row=document.createElement('tr');cell(row,item.title+'\n'+item.id);cell(row,[item.subject,item.grade,item.textbook_version,item.chapter,item.document_role].filter(Boolean).join(' · '));cell(row,item.status+'\n分块 '+item.chunk_count+' / 公式 '+item.formula_count+' / 待审 '+item.pending_formula_count);cell(row,item.authorization_status);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='编辑文档';button.onclick=()=>selectDocument(item);action.appendChild(button);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
async function saveDocument(){try{const id=$('documentId').value;if(!id)throw new Error('请先选择文档');const body={title:$('documentTitle').value.trim(),subject:$('documentSubject').value.trim()||null,grade:$('documentGrade').value.trim()||null,textbook_version:$('documentVersion').value.trim()||null,chapter:$('documentChapter').value.trim()||null,document_role:$('documentRole').value.trim()||null,authorization_status:$('documentAuthorization').value};if($('documentStatus').value)body.status=$('documentStatus').value;const data=await api('/admin/knowledge/documents/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(body)});selectDocument(data);await loadDocuments()}catch(e){show({error:e.message})}}
async function loadIntegrity(){try{const p=new URLSearchParams();if($('integritySubject').value)p.set('subject',$('integritySubject').value);show(await api('/admin/knowledge/integrity?'+p))}catch(e){show({error:e.message})}}
async function loadFormulaQueue(reset=false){try{if(reset)formulaOffset=0;const p=new URLSearchParams({review_status:$('formulaFilterStatus').value,subject:$('formulaSubject').value,offset:formulaOffset,limit:pageSize});if($('formulaConfidence').value)p.set('confidence_max',$('formulaConfidence').value);const data=await api('/admin/knowledge/formulas?'+p);const body=$('formulaRows');body.replaceChildren();for(const item of data.items){const row=document.createElement('tr');cell(row,item.document_title+'\n'+(item.chapter||''));cell(row,item.formula_latex);cell(row,item.ocr_confidence==null?'—':item.ocr_confidence.toFixed(3));cell(row,item.review_status);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='审核';button.onclick=()=>selectFormula(item);action.appendChild(button);body.appendChild(row)}$('formulaMeta').textContent=`${data.offset+1}-${Math.min(data.offset+data.items.length,data.total)} / ${data.total}`;show(data)}catch(e){show({error:e.message})}}
function changeFormulaPage(direction){const next=Math.max(0,formulaOffset+direction*pageSize);if(next===formulaOffset)return;formulaOffset=next;loadFormulaQueue()}
function selectFormula(item){$('formulaId').value=item.id;$('formulaLatex').value=item.formula_latex||'';$('formulaStatus').value=item.review_status||'pending';$('formulaNote').value=item.review_note||'';show(item)}
async function saveFormulaReview(){try{const body={review_status:$('formulaStatus').value,formula_latex:$('formulaLatex').value,review_note:$('formulaNote').value||null};show(await api('/admin/knowledge/formulas/'+encodeURIComponent($('formulaId').value),{method:'PATCH',body:JSON.stringify(body)}));await loadFormulaQueue()}catch(e){show({error:e.message})}}
function clearEdgeEditor(){$('edgeId').value='';$('source').value='';$('target').value='';$('edgeType').value='prerequisite';$('edgeExplanation').value='管理员维护的知识关系'}
function selectEdge(item){$('edgeId').value=item.id;$('source').value=item.source_node_id;$('target').value=item.target_node_id;$('edgeType').value=item.edge_type;$('edgeExplanation').value=item.explanation;show(item)}
async function saveEdge(){try{const id=$('edgeId').value;const body=id?{edge_type:$('edgeType').value,explanation:$('edgeExplanation').value}:{source_node_id:$('source').value,target_node_id:$('target').value,edge_type:$('edgeType').value,explanation:$('edgeExplanation').value};const data=await api(id?'/admin/knowledge/edges/'+encodeURIComponent(id):'/admin/knowledge/edges',{method:id?'PATCH':'POST',body:JSON.stringify(body)});selectEdge(data);await loadEdges()}catch(e){show({error:e.message})}}
async function loadEdges(){try{const p=new URLSearchParams();if($('edgeNodeFilter').value)p.set('node_id',$('edgeNodeFilter').value);const data=await api('/admin/knowledge/edges?'+p);const body=$('edgeRows');body.replaceChildren();for(const item of data){const row=document.createElement('tr');cell(row,item.source_node_id);cell(row,item.edge_type);cell(row,item.target_node_id);cell(row,item.explanation);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='编辑';button.onclick=()=>selectEdge(item);action.appendChild(button);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
async function deleteEdge(){try{const id=$('edgeId').value;if(!id)throw new Error('请先选择关系');await api('/admin/knowledge/edges/'+encodeURIComponent(id),{method:'DELETE'});clearEdgeEditor();await loadEdges();show({deleted:id})}catch(e){show({error:e.message})}}
async function reviewFeedback(){try{show(await api('/admin/feedback/'+encodeURIComponent($('feedbackId').value),{method:'PATCH',body:JSON.stringify({status:$('feedbackStatus').value,review_note:$('feedbackNote').value})}))}catch(e){show({error:e.message})}}
async function loadFeedback(){try{show(await api('/admin/feedback?status=pending'))}catch(e){show({error:e.message})}}
async function adjustCredits(){try{show(await api('/admin/credits/'+encodeURIComponent($('userId').value)+'/adjust',{method:'POST',body:JSON.stringify({amount:Number($('amount').value),reason:$('reason').value})}))}catch(e){show({error:e.message})}}
async function loadCosts(){try{const p=new URLSearchParams();if($('costStart').value)p.set('start_at',new Date($('costStart').value).toISOString());if($('costEnd').value)p.set('end_at',new Date($('costEnd').value).toISOString());if($('costFeature').value)p.set('feature',$('costFeature').value);if($('costProvider').value)p.set('provider',$('costProvider').value);show(await api('/admin/model-costs?'+p))}catch(e){show({error:e.message})}}
async function loadOperationalAlerts(){try{show(await api('/admin/operational-alerts'))}catch(e){show({error:e.message})}}
function selectContribution(item){$('contributionId').value=item.id;$('contributionNote').value=item.review_note||'';show(item)}
async function loadContributions(){try{const p=new URLSearchParams();if($('contributionStatus').value)p.set('contribution_status',$('contributionStatus').value);const data=await api('/admin/contributions?'+p);const body=$('contributionRows');body.replaceChildren();for(const item of data){const row=document.createElement('tr');cell(row,item.title+'\n'+item.content.slice(0,180),'preview');cell(row,item.contribution_type+' / '+item.status);cell(row,JSON.stringify(item.ai_review));cell(row,item.user_id);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='选择';button.onclick=()=>selectContribution(item);action.appendChild(button);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
async function reviewContribution(){try{const id=$('contributionId').value;if(!id)throw new Error('请先选择投稿');const body={decision:$('contributionDecision').value,review_note:$('contributionNote').value,reward_amount:Number($('contributionReward').value)};show(await api('/admin/contributions/'+encodeURIComponent(id)+'/review',{method:'POST',body:JSON.stringify(body)}));await loadContributions()}catch(e){show({error:e.message})}}
async function retryContribution(){try{const id=$('contributionId').value;if(!id)throw new Error('请先选择投稿');show(await api('/admin/contributions/'+encodeURIComponent(id)+'/retry',{method:'POST'}));await loadContributions()}catch(e){show({error:e.message})}}
async function settleContributionRewards(){try{show(await api('/admin/contributions/rewards/settle',{method:'POST'}))}catch(e){show({error:e.message})}}
async function createSchool(){try{const data=await api('/organizations/schools',{method:'POST',body:JSON.stringify({name:$('schoolName').value,code:$('schoolCode').value})});$('schoolId').value=data.id;show(data)}catch(e){show({error:e.message})}}
async function loadClasses(){try{const id=$('schoolId').value;if(!id)throw new Error('请输入学校 ID');show(await api('/organizations/schools/'+encodeURIComponent(id)+'/classes'))}catch(e){show({error:e.message})}}
async function createClassroom(){try{const id=$('schoolId').value;if(!id)throw new Error('请输入学校 ID');const body={name:$('className').value,grade:$('classGrade').value||null,academic_year:$('classYear').value};const data=await api('/organizations/schools/'+encodeURIComponent(id)+'/classes',{method:'POST',body:JSON.stringify(body)});$('classId').value=data.id;show(data)}catch(e){show({error:e.message})}}
async function createInvite(){try{const schoolId=$('schoolId').value;if(!schoolId)throw new Error('请输入学校 ID');const body={class_id:$('classId').value||null,member_role:$('inviteRole').value,max_uses:Number($('inviteUses').value),expires_hours:Number($('inviteHours').value)};show(await api('/organizations/schools/'+encodeURIComponent(schoolId)+'/invites',{method:'POST',body:JSON.stringify(body)}))}catch(e){show({error:e.message})}}
async function loadClassOverview(){try{const id=$('classId').value;if(!id)throw new Error('请输入班级 ID');show(await api('/organizations/classes/'+encodeURIComponent(id)+'/overview'))}catch(e){show({error:e.message})}}
function selectedBoolean(id){return $(id).value==='true'}
async function approvePilotEnrollment(){try{const schoolId=$('schoolId').value.trim();const userId=$('pilotParticipantId').value.trim();if(!schoolId||!userId)throw new Error('请输入学校 ID 和参与者用户 ID');const body={user_id:userId,school_authorization_confirmed:selectedBoolean('pilotSchoolAuthorized'),voluntary_participation_confirmed:selectedBoolean('pilotVoluntary'),guardian_authorization_required:selectedBoolean('pilotGuardianRequired'),guardian_authorization_confirmed:selectedBoolean('pilotGuardianConfirmed'),approval_basis:$('pilotApprovalBasis').value.trim()};const data=await api('/organizations/schools/'+encodeURIComponent(schoolId)+'/pilot-approvals',{method:'POST',body:JSON.stringify(body)});show(data);await loadPilotApprovals()}catch(e){show({error:e.message})}}
async function loadPilotApprovals(){try{const schoolId=$('schoolId').value.trim();if(!schoolId)throw new Error('请输入学校 ID');const data=await api('/organizations/schools/'+encodeURIComponent(schoolId)+'/pilot-approvals');const body=$('pilotApprovalRows');body.replaceChildren();for(const item of data){const row=document.createElement('tr');cell(row,item.username+'\n'+item.user_id);cell(row,item.status);cell(row,'学校 '+(item.school_authorization_confirmed?'是':'否')+' / 自愿 '+(item.voluntary_participation_confirmed?'是':'否')+' / 监护人 '+(item.guardian_authorization_required?(item.guardian_authorization_confirmed?'已确认':'未确认'):'无需'));cell(row,item.approval_basis);const action=cell(row,'');const button=document.createElement('button');button.className='danger small';button.textContent='撤销';button.onclick=()=>revokePilotEnrollment(item.user_id);action.appendChild(button);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
async function revokePilotEnrollment(userId=null){try{const schoolId=$('schoolId').value.trim();const participantId=userId||$('pilotParticipantId').value.trim();if(!schoolId||!participantId)throw new Error('请输入学校 ID 和参与者用户 ID');await api('/organizations/schools/'+encodeURIComponent(schoolId)+'/pilot-approvals/'+encodeURIComponent(participantId),{method:'DELETE'});$('pilotParticipantId').value=participantId;show({revoked:true,user_id:participantId});await loadPilotApprovals()}catch(e){show({error:e.message})}}
async function createCampaign(){try{const body={name:$('campaignName').value,amount:Number($('campaignAmount').value),school_id:$('schoolId').value||null,expires_hours:720,max_redemptions:Number($('campaignMax').value),per_user_limit:1,code_count:Number($('campaignCodes').value),code_max_uses:1};show(await api('/admin/credits/campaigns',{method:'POST',body:JSON.stringify(body)}))}catch(e){show({error:e.message})}}
async function loadCampaigns(){try{show(await api('/admin/credits/campaigns'))}catch(e){show({error:e.message})}}
function pilotParams(){const p=new URLSearchParams();if($('pilotStart').value)p.set('start_at',new Date($('pilotStart').value).toISOString());if($('pilotEnd').value)p.set('end_at',new Date($('pilotEnd').value).toISOString());return p}
function pilotUserIds(){return lines('pilotCleanupIds')}
async function loadPilotMetrics(){try{show(await api('/admin/pilot/metrics?'+pilotParams()))}catch(e){show({error:e.message})}}
async function downloadPilotExport(){try{const data=await api('/admin/pilot/export?'+pilotParams());const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='qingkui-pilot-anonymous.json';link.click();URL.revokeObjectURL(link.href);show(data)}catch(e){show({error:e.message})}}
async function previewPilotCleanup(){try{const data=await api('/admin/pilot/cleanup/preview',{method:'POST',body:JSON.stringify({user_ids:pilotUserIds()})});$('pilotCleanupCount').value=data.eligible_count;show(data)}catch(e){show({error:e.message})}}
async function executePilotCleanup(){try{const body={user_ids:pilotUserIds(),expected_count:Number($('pilotCleanupCount').value),confirmation:$('pilotCleanupConfirmation').value};show(await api('/admin/pilot/cleanup',{method:'POST',body:JSON.stringify(body)}));$('pilotCleanupIds').value='';$('pilotCleanupConfirmation').value='';await loadUsers()}catch(e){show({error:e.message})}}
async function loadLogs(){try{show(await api('/admin/audit-logs'))}catch(e){show({error:e.message})}}
async function loadUsers(){try{const p=new URLSearchParams();if($('userQ').value)p.set('q',$('userQ').value);if($('userRole').value)p.set('role',$('userRole').value);if($('userActive').value)p.set('is_active',$('userActive').value);const data=await api('/admin/users?'+p);const body=$('userRows');body.replaceChildren();for(const item of data){const row=document.createElement('tr');cell(row,item.username+'\n'+item.nickname+'\n'+item.id);const roleCell=cell(row,'');const role=document.createElement('select');for(const value of ['student','content_admin','admin']){const option=document.createElement('option');option.value=value;option.textContent=value;option.selected=value===item.role;role.appendChild(option)}roleCell.appendChild(role);cell(row,item.is_active?'正常':'冻结');cell(row,item.balance==null?'—':item.balance);const actions=cell(row,'');const statusButton=document.createElement('button');statusButton.className=item.is_active?'danger small':'small';statusButton.textContent=item.is_active?'冻结':'解冻';statusButton.onclick=()=>setUserStatus(item.id,!item.is_active);actions.appendChild(statusButton);const roleButton=document.createElement('button');roleButton.className='secondary small';roleButton.textContent='保存角色';roleButton.onclick=()=>setUserRole(item.id,role.value);actions.appendChild(roleButton);const creditButton=document.createElement('button');creditButton.className='secondary small';creditButton.textContent='调整额度';creditButton.onclick=()=>{$('userId').value=item.id;window.scrollTo({top:0,behavior:'smooth'})};actions.appendChild(creditButton);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
async function setUserStatus(id,isActive){try{show(await api('/admin/users/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({is_active:isActive})}));await loadUsers()}catch(e){show({error:e.message})}}
async function setUserRole(id,role){try{show(await api('/admin/users/'+encodeURIComponent(id)+'/role',{method:'PATCH',body:JSON.stringify({role})}));await loadUsers()}catch(e){show({error:e.message})}}
async function loadOcrTasks(){try{const p=new URLSearchParams();if($('ocrQ').value)p.set('q',$('ocrQ').value);if($('ocrFilterStatus').value)p.set('status',$('ocrFilterStatus').value);if($('ocrReview').value)p.set('requires_review',$('ocrReview').value);const data=await api('/admin/ocr-tasks?'+p);const body=$('ocrRows');body.replaceChildren();for(const item of data){const row=document.createElement('tr');cell(row,item.status+(item.requires_review?' · 待复核':''));cell(row,item.user_id+'\n'+item.mistake_id);cell(row,item.confidence==null?'—':item.confidence.toFixed(3));cell(row,item.created_at);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='查看';button.onclick=()=>selectOcrTask(item.id);action.appendChild(button);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
async function selectOcrTask(id){try{const data=await api('/admin/ocr-tasks/'+encodeURIComponent(id));$('ocrTaskId').value=data.id;show(data)}catch(e){show({error:e.message})}}
async function ocrTaskAction(action){try{const id=$('ocrTaskId').value;if(!id)throw new Error('请先选择 OCR 任务');show(await api('/admin/ocr-tasks/'+encodeURIComponent(id)+'/'+action,{method:'POST'}));await loadOcrTasks()}catch(e){show({error:e.message})}}
async function loadMistakes(){try{const p=new URLSearchParams();if($('mistakeQ').value)p.set('q',$('mistakeQ').value);if($('mistakeFilterStatus').value)p.set('review_status',$('mistakeFilterStatus').value);if($('mistakeFilterLink').value)p.set('link_status',$('mistakeFilterLink').value);const data=await api('/admin/mistakes?'+p);const body=$('mistakeRows');body.replaceChildren();for(const item of data){const row=document.createElement('tr');cell(row,(item.corrected_text||item.question_text||'未识别').slice(0,260),'preview');cell(row,item.review_status+' / '+item.link_status);cell(row,item.user_id);const action=cell(row,'');const button=document.createElement('button');button.className='small';button.textContent='审核';button.onclick=()=>selectMistake(item);action.appendChild(button);body.appendChild(row)}show(data)}catch(e){show({error:e.message})}}
function selectMistake(item){$('mistakeId').value=item.id;$('mistakeReviewStatus').value=['approved','needs_review','rejected','confirmed'].includes(item.review_status)?item.review_status:'needs_review';$('mistakeCategory').value=item.error_category||'';$('mistakeLinkStatus').value=item.link_status||'pending';$('mistakeNodeId').value=item.knowledge_node_id||'';$('mistakeNote').value=item.error_note||'';show(item)}
async function saveMistakeReview(){try{const body={review_status:$('mistakeReviewStatus').value,link_status:$('mistakeLinkStatus').value,error_note:$('mistakeNote').value||null};if($('mistakeCategory').value)body.error_category=$('mistakeCategory').value;if($('mistakeNodeId').value)body.knowledge_node_id=$('mistakeNodeId').value;show(await api('/admin/mistakes/'+encodeURIComponent($('mistakeId').value),{method:'PATCH',body:JSON.stringify(body)}));await loadMistakes()}catch(e){show({error:e.message})}}
if(token)$('status').textContent='已设置令牌';
</script></body></html>'''


def admin_page() -> HTMLResponse:
    return HTMLResponse(
        ADMIN_HTML,
        headers={
            "Cache-Control": "no-store",
            "Content-Security-Policy": (
                "default-src 'none'; connect-src 'self'; img-src 'self' data:; "
                "style-src 'unsafe-inline'; script-src 'unsafe-inline'; base-uri 'none'; "
                "form-action 'none'; frame-ancestors 'none'"
            ),
            "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
            "Referrer-Policy": "no-referrer",
            "X-Content-Type-Options": "nosniff",
            "X-Frame-Options": "DENY",
        },
    )
